### ISSUE TITLE
I can't download the Dataset

### ISSUE THREAD

**Issue by Qijian-Z** [chunbaobao/Deep-JSCC-PyTorch#1]
Excuse me, I can't download the dataset from http://www.image-net.org/challenges/LSVRC/2012/downloads for 404.

**Comment by chunbaobao** [comment]
> Excuse me, I can't download the dataset from http://www.image-net.org/challenges/LSVRC/2012/downloads for 404.

I just check it out and found the previous website has been changed to https://image-net.org/challenges/LSVRC/2012/2012-downloads. The `README` and `dataset.py` have been modified.

**Comment by Qijian-Z** [comment]
Thank you for your prompt response, and everything seems to have been resolved.
十分抱歉，这么晚的时间打扰到您。同时，十分感谢您的帮助，如果有什么问题请允许我再向您提问。

**Comment by chunbaobao** [comment]
welcome!
