### ISSUE TITLE
The  final operation of autoencoder layers compared with traditional operation like  qam-ldpc

### ISSUE THREAD

**Issue by LimFang** [chunbaobao/Deep-JSCC-PyTorch#10]
There is a concern regarding how to transmit complex symbols from the last layer of the autoencoder to the receiver, which typically handles a bitstream of 0s and 1s. Current applications rely on such bitstream transmission. If we adopt complex symbols with QAM and LDPC, what would the true meaning of JSCC be in this context? Additionally, GNU Radio has been used in the IC.UK project "Deepwive" for JSCC.

**Comment by chunbaobao** [comment]
I think the key point is that QAM is a modulation method used across all comm systems, but LDPC is a channel coding technique that has been replaced by JSCC in this context. As for the previous JSCC, the system modeling was often simplified, including aspects like power allocation, the handling of complex symbols, and even the modulation itself. Thats what recent work focus on.

**Comment by LimFang** [comment]
i can not agree more. And that is why i was really confused before as simplfied models just sent fp32 or fp16. There is a real application for jscc deployed on tensor-rt. So in that case, may 0 1 codes are exactely transimited?

**Comment by chunbaobao** [comment]
Actually, the fp32 or fp16 data sent from the models is practical in some way, where the channel represents the whole equivalent digital channel $X(f)$ as shown below:  
![image](https://github.com/user-attachments/assets/d52a89c8-4eeb-4452-babe-e415d7b13c97)  

As for the TensorRT you mentioned, sorry that I am not familiar with that.

**Comment by LimFang** [comment]
Thank you for your response. I look forward to seeing any future practical work based on JSCC.
