### ISSUE TITLE
Slow training

### ISSUE THREAD

**Issue by lalalalalal0** [chunbaobao/Deep-JSCC-PyTorch#11]
When training the model, I find that GPU utilisation is low most of the time, how should I increase GPU utilisation.

**Comment by chunbaobao** [comment]
Consider increasing `params['init_lr']` and `params['batch_size']` in the code. The configuration follows the original paper, but it may not match the current computational capacity.

**Comment by lalalalalal0** [comment]
Thanks for the reply, I found that setting the params ['num_worker'] to 0 increases the speed of the run.
