### ISSUE TITLE
Issue with Unrecognized Argument and Dimension Mismatch Error

### ISSUE THREAD

**Issue by aomenfage** [chunbaobao/Deep-JSCC-PyTorch#3]
Hello,

I encountered a couple of issues while trying to run a script from this repository. I was using the following command:
`python eval.py --channel 'AWGN' --saved ./saved/cifar10_1000_0.33_100.00_40.pth --snr 20 --test_image ./demo/kodim08.png
`
The first issue is with an unrecognized argument error. The full error message is:
`eval.py: error: unrecognized arguments: --ratio_list 1/3
`
When I remove the `--ratio_list` argument, I face another error related to tensor dimensions. The error message is:
`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 3, 5, 5], but got 3-dimensional input of size [3, 512, 768] instead.`
This error seems to occur because the script expects a 4-dimensional input, but the provided input is only 3-dimensional.
Could you please provide some guidance on how to resolve these issues? Is there a specific way to format the input or modify the command to avoid these errors?
Thank you for your assistance.

**Comment by chunbaobao** [comment]
The 4-dimensional weight [16, 3, 5, 5] suggests that $C_{in}$ equals 3, aligning with the first dimension in [3, 512, 768]. I suspect the error stems from using an outdated version of PyTorch. Newer versions support input sizes of $(C_{in},H_{in},W_{in})$ without explicitly specifying the batch_size, whereas older versions require dimensions in the form $((N,C_{in},H_{in},W_{in})$. You can either update your PyTorch version or apply the following fix: add `test_image = test_image.unsqueeze(dim=0)` to append a batch dimension at the beginning after `test_image = transform(test_image)` in `eval.py`.

**Comment by chunbaobao** [comment]
By the way, the unrecognized arguments error has been fixed.

**Comment by aomenfage** [comment]
> By the way, the unrecognized arguments error has been fixed.

Thank you so much. Having benefited from your assistance, I am now reaching out to kindly request if you could share the pre-trained model. I believe that access to this model would significantly enhance my understanding and enable me to achieve better results in my current project.

**Comment by chunbaobao** [comment]
Some simple pre-trained models are shared in `./saved`.

**Comment by LihanChen2004** [comment]
> The 4-dimensional weight [16, 3, 5, 5] suggests that 4 维权重 [16,3,5,5] 表明 C i n equals 3, aligning with the first dimension in [3, 512, 768]. I suspect the error stems from using an outdated version of PyTorch. Newer versions support input sizes of 等于 3，与 [3, 512, 768] 中的第一个维度对齐。我怀疑该错误源于使用过时版本的 PyTorch。较新的版本支持输入大小 ( C i n , H i n , W i n ) without explicitly specifying the batch_size, whereas older versions require dimensions in the form 没有明确指定batch_size，而旧版本需要以下形式的维度 ( ( N , C i n , H i n , W i n ) . You can either update your PyTorch version or apply the following fix: add `test_image = test_image.unsqueeze(dim=0)` to append a batch dimension at the beginning after `test_image = transform(test_image)` in `eval.py`.。您可以更新 PyTorch 版本或应用以下修复：添加 test_image = test_image.unsqueeze(dim=0) 以在 eval.py 中的 test_image = transform(test_image) 之后的开头附加批处理维度。

Can you provide your Python and Torch version?

When I use Python==3.8 and Torch==2.4.1 to run single_visualization.ipynb, I also get an error at 

```sh
RuntimeError                              Traceback (most recent call last)
Cell In[227], [line 10](vscode-notebook-cell:?execution_count=227&line=10)
      [8](vscode-notebook-cell:?execution_count=227&line=8)         psnr_all += get_psnr(demo_image, gt)
      [9](vscode-notebook-cell:?execution_count=227&line=9)     demo_image = image_normalization('normalization')(demo_image)
---> [10](vscode-notebook-cell:?execution_count=227&line=10)     demo_image = torch.cat([test_image, demo_image], dim=1)
     [11](vscode-notebook-cell:?execution_count=227&line=11)     demo_image = demo_image.numpy()
     [12](vscode-notebook-cell:?execution_count=227&line=12) plt.imshow(demo_image.transpose(1, 2, 0))

RuntimeError: Tensors must have same number of dimensions: got 3 and 4
```

**Comment by chunbaobao** [comment]
python==3.8.0 with torch==1.12.1
