### ISSUE TITLE
模型文件的命名

### ISSUE THREAD

**Issue by fake-learn** [chunbaobao/Deep-JSCC-PyTorch#4]
你好，想请教一下cifar10_2000_0.33_100.00_64_40.pth类似的模型参数文件命名里各个参数的含义是什么，例如这里的2000, 100,  64，40是什么意思呢

**Comment by chiyuyaer** [comment]
args.dataset, args.epochs, ratio, snr, args.batch_size, c，分别代表这个意思，代码里有写

**Comment by fake-learn** [comment]
谢谢您的解答，我已经在代码中找到了对应的部分。
