### ISSUE TITLE
作者都是保存的模型都是在snr=100dB的条件下进行训练的吗？为什么评估出来的效果只有10dB左右，这个效果是不是不好？怎样才能提高模型的效果呢？

### ISSUE THREAD

**Issue by chiyuyaer** [chunbaobao/Deep-JSCC-PyTorch#5]

**Comment by chiyuyaer** [comment]
原来是在cifar10上训练的模型效果比较差，为什么imagenet上训练的效果要好很多呢？

**Comment by chunbaobao** [comment]
cifar10数据量小当然训练效果比较差，至于你说的评估结果比较差，第一个原因，提供的模型只是简单的训练结果，还有些欠拟合，第二semantic communication范式都有一个趋势：在高snr训练的模型在低snr的表现都很差。
