### ISSUE TITLE
关于训练高分辨率图像数据集

### ISSUE THREAD

**Issue by xiangyanya** [chunbaobao/Deep-JSCC-PyTorch#9]
你好，我用您的模型训练高分辨率图像数据集DIV2K,但是发现测试的时候，psnr不随snr的变高而变好，反而数值相似，请问你遇到这个问题了吗

**Comment by chunbaobao** [comment]
没有在这个数据集上做过实验，不过我猜测可能对于高分辨率图像需要使用更高的传输功率P（默认为1）或者更高精度的浮点数以防止计算float数时归零

**Comment by xiangyanya** [comment]
好的，我还想请问一下，你现在可以复现和原文一样的PSNR结果了吗？还有，你曾在除了CIFAR10之外的数据集做过实验吗？感谢！


小妖怪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chunbaobao/Deep-JSCC-PyTorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月14日(星期天) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chunbaobao/Deep-JSCC-PyTorch] 关于训练高分辨率图像数据集 (Issue #9)





 
没有在这个数据集上做过实验，不过我猜测可能对于高分辨率图像需要使用更高的传输功率P（默认为1）或者更高精度的浮点数以防止计算float数时归零

**Comment by xiangyanya** [comment]
> 没有在这个数据集上做过实验，不过我猜测可能对于高分辨率图像需要使用更高的传输功率P（默认为1）或者更高精度的浮点数以防止计算floa

**Comment by xiangyanya** [comment]
谢谢你，是有用的
